source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD'
pod 'SQKDataKit'
pod 'Reachability'
pod 'CLLocationManager-blocks'
pod 'SDWebImage', '~>3.7'
pod 'FontAwesomeIconFactory'
pod 'DZNEmptyDataSet'
pod 'FLAnimatedImage', '~> 1.0'
pod 'ActionSheetPicker-3.0', '~> 1.5.1'
pod 'Braintree', '3.9.6'
#pod 'Braintree/Apple-Pay'
pod 'CardIO'
pod 'MTBBarcodeScanner'
pod 'FBSDKCoreKit'
pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'RMDateSelectionViewController', '~> 2.0.1'
pod 'DateTools'
pod 'EAIntroView', '~> 2.8.0'
pod 'Fabric'
pod 'Crashlytics'